import * as React from "react";
import Head from "next/head";
import styles from "@/styles/Inicio.module.css";
import Footer from "@/components/Footer/Footer";
import Carrito from "@/components/Carrito/Carrito";
import { useRouter } from "next/router";
import { productos } from "@/utils/productos";

export default function Inicio() {
  const router = useRouter();
  const [position, setPosition] = React.useState(0);
  const [mostrarCarrito, setMostrarCarrito] = React.useState(false);

  const toggle = () => setMostrarCarrito((prev) => !prev);

  const moveCarousel = (direction: string) => {
    let position = 0;

    const itemWidth = 1000;
    const maxPosition = 3 * itemWidth;

    if (direction === "next" && position > -maxPosition) {
      setPosition((prev) => prev - itemWidth);
    } else if (direction === "prev" && position < 0) {
      setPosition((prev) => prev + itemWidth);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.navbar}>
          <div className={styles.logo}>
            <img src="../images/logoAndaia.png" alt="Logo" />
            <span> ANDAIA </span>
          </div>
          <nav className="nav">
            <ul>
              <li>
                <a className={styles.a} href="">
                  WishList
                </a>
              </li>
              <li>
                <a className={styles.a} href="">
                  Perfil
                </a>
              </li>
              <li>
                <div className={styles.iconCart} onClick={toggle}>
                  <svg
                    className={styles.svg}
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke="currentColor"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M5 4h1.5L9 16m0 0h8m-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm-8.5-3h9.25L19 7H7.312"
                    />
                  </svg>
                  <span>0</span>
                </div>
              </li>
            </ul>
          </nav>
        </div>
        <div className={styles.inicio}>
          <div className={styles.col_2}>
            <img src="../images/inicio1.png" alt="inicio1" />
          </div>
        </div>
      </div>
      <div className={styles.categories}>
        <div className={styles.small_container}>
          <div
            className={styles.category_carousel}
            style={{ transform: `translateX(${position}px)` }}
          >
            <div className={[styles.category_item, styles.col_3].join(" ")}>
              <img src="../images/tops/tops.jpeg" alt="Categoria: tops" />
            </div>
            <div className={(styles.category_item, styles.col_3b)}>
              <img
                src="../images/bottoms/bottoms.jpeg"
                alt="Categoria: bottoms"
              />
            </div>
            <div className={[styles.category_item, styles.col_3].join(" ")}>
              <img src="../images/shoes/shoes.jpeg" alt="Categoria: shoes" />
            </div>
            <div className={[styles.category_item, styles.col_3].join(" ")}>
              <img
                src="../images/jewerly/jewlery.jpeg"
                alt="Categoria: jewerly"
              />
            </div>
            <div className={[styles.category_item, styles.col_3].join(" ")}>
              <img
                src="../images/accessories/accessories.jpeg"
                alt="Categoria: accessories"
              />
            </div>
            <div className={[styles.category_item, styles.col_3].join(" ")}>
              <img src="../images/more/more.jpeg" alt="Categoria: more" />
            </div>
          </div>
        </div>
        <div className={styles.carousel_buttons}>
          <button className={styles.prev} onClick={() => moveCarousel("prev")}>
            &#10094;
          </button>
          <button className={styles.next} onClick={() => moveCarousel("next")}>
            &#10095;
          </button>
        </div>
      </div>

      {/* <!--- productos --> */}
      <div className={styles.small_container}>
        <h1 className={styles.titulo}>Algunos productos</h1>
        <div className={styles.row}>
          {productos.map((producto) => (
            <div
              className={styles.col_4}
              onClick={() => router.push(`/productos/${producto.id}`)}
            >
              <a
                className={styles.a}
                onClick={() => router.push(`/productos/${producto.id}`)}
              >
                <img src={producto.img} />
                {producto.nombre}
              </a>
              <p>${producto.precio}</p>
            </div>
          ))}
        </div>
      </div>

      {mostrarCarrito && <Carrito />}
      <Footer />
    </>
  );
}
