import Head from "next/head";
import styles from "@/styles/Login.module.css";
import { useRouter } from "next/router";

export default function Login() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header_container}>
        <div className={styles.page_name}>ANDAIA</div>
        <div className={styles.regresar_button_container}>
          <button
            className={styles.regresar_button}
            onClick={() => router.push("/")}
          >
            Regresar
          </button>
        </div>
      </header>
      <div className={styles.login_container}>
        <h2>Iniciar sesión</h2>
        <form action="#" method="POST" className={styles.login_formulario}>
          {/*  <!-- Usuario --> */}
          <div className={styles.formulario}>
            <label for="username">Usuario:</label>
            <input type="text" id="username" name="username" required />
          </div>
          {/* <!-- Contraseña --> */}
          <div className={styles.formulario}>
            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password" required />
          </div>
          {/* <!-- Botón de iniciar sesión --> */}
          <div className={styles.formulario}>
            <button type="submit" className={styles.login_button}>
              Iniciar sesión
            </button>
          </div>
        </form>

        {/* <!-- Enlace de "Olvidé contraseña" fuera del formulario --> */}
        <div className={styles.olvideContrasena_container}>
          <button
            className={styles.olvideContrasena_button}
            onClick={() => router.push("/olvidar-contrasena")}
          >
            Olvidé mi contraseña
          </button>
        </div>
      </div>
    </>
  );
}
